---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: andersson007
name: my_collection
version: 0.1.0
readme: README.md
authors:
  - Andersson007 (github.com/Andersson007)
description: Dummy collection
license_file: LICENSE
tags:
  - dummy
repository: https://github.com/Andersson007/andersson007.my_collection
homepage: https://github.com/Andersson007/andersson007.my_collection
issues: https://github.com/Andersson007/andersson007.my_collection/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
